set_property SRC_FILE_INFO {cfile:/home/suhail/Documents/UART/UART.srcs/constrs_1/new/constraints.xdc rfile:../../../UART.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports uart_rtl_txd]
